# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pic', models.ImageField(default='pic/folder/none/no-img.jpg', upload_to='pic/folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body', models.IntegerField(blank=True, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=64, null=True)),
                ('current_kids', models.IntegerField(blank=True, null=True)),
                ('future_kids', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('smoke', models.IntegerField(blank=True, null=True)),
                ('drink', models.IntegerField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=64, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('activity', models.IntegerField()),
                ('frugality', models.IntegerField()),
                ('pragmaticism', models.IntegerField()),
                ('family', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seeking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body', models.IntegerField(blank=True, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=64, null=True)),
                ('current_kids', models.IntegerField(blank=True, null=True)),
                ('future_kids', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('smoke', models.IntegerField(blank=True, null=True)),
                ('drink', models.IntegerField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=64, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('activity', models.IntegerField()),
                ('frugality', models.IntegerField()),
                ('pragmaticism', models.IntegerField()),
                ('family', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Wink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wink_recipient', to='match_dot_com.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wink', to='match_dot_com.User')),
            ],
        ),
        migrations.AddField(
            model_name='seeking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seeking', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pics', to='match_dot_com.User'),
        ),
    ]
