# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pic', models.FileField(upload_to='img')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pic', models.FileField(default='img/default.png', upload_to='img')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('message_read', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body', models.IntegerField(blank=True, null=True)),
                ('relationship_status', models.IntegerField(blank=True, null=True)),
                ('current_kids', models.IntegerField(blank=True, null=True)),
                ('future_kids', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('smoke', models.IntegerField(blank=True, null=True)),
                ('drink', models.IntegerField(blank=True, null=True)),
                ('religion', models.IntegerField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('activity', models.IntegerField(blank=True, null=True)),
                ('frugality', models.IntegerField(blank=True, null=True)),
                ('pragmaticism', models.IntegerField(blank=True, null=True)),
                ('family', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seeking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=64, null=True)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('height_min', models.IntegerField(blank=True, null=True)),
                ('height_max', models.IntegerField(blank=True, null=True)),
                ('body', models.IntegerField(blank=True, null=True)),
                ('deal_body', models.IntegerField(blank=True)),
                ('relationship_status', models.IntegerField(blank=True, null=True)),
                ('deal_relationship_status', models.IntegerField(blank=True)),
                ('current_kids', models.IntegerField(blank=True, null=True)),
                ('deal_current_kids', models.IntegerField(blank=True)),
                ('future_kids', models.IntegerField(blank=True, null=True)),
                ('deal_future_kids', models.IntegerField(blank=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('deal_education', models.IntegerField(blank=True)),
                ('smoke', models.IntegerField(blank=True, null=True)),
                ('deal_smoke', models.IntegerField(blank=True)),
                ('drink', models.IntegerField(blank=True, null=True)),
                ('deal_drink', models.IntegerField(blank=True)),
                ('religion', models.IntegerField(blank=True, null=True)),
                ('deal_religion', models.IntegerField(blank=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('deal_salary', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('zipcode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wink_seen', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wink_recipient', to='match_dot_com.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wink', to='match_dot_com.User')),
            ],
        ),
        migrations.AddField(
            model_name='seeking',
            name='seeking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seeking', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pics', to='match_dot_com.User'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gallery', to='match_dot_com.User'),
        ),
    ]
