# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_body',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_current_kids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_drink',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_education',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_future_kids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_relationship_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_religion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='deal_smoke',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
