# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_read',
            field=models.NullBooleanField(default=False),
        ),
    ]
