# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0002_auto_20170329_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='user_pic',
            field=models.FileField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='seeking_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_seeking', to='match_dot_com.User'),
        ),
    ]
