# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0002_user_zipcode'),
        ('match_dot_com', '0003_auto_20170327_2356'),
    ]

    operations = [
    ]
