# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0004_merge_20170328_1321'),
        ('match_dot_com', '0004_merge_20170328_1305'),
    ]

    operations = [
    ]
