# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0005_merge_20170328_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='user_pic',
            field=models.FileField(upload_to='apps/match_dot_com/static/match_dot_com/img'),
        ),
    ]
