# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0007_auto_20170328_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seeking',
            old_name='age',
            new_name='age_max',
        ),
        migrations.RenameField(
            model_name='seeking',
            old_name='height',
            new_name='age_min',
        ),
        migrations.RemoveField(
            model_name='seeking',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='seeking',
            name='family',
        ),
        migrations.RemoveField(
            model_name='seeking',
            name='frugality',
        ),
        migrations.RemoveField(
            model_name='seeking',
            name='pragmaticism',
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_body',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_current_kids',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_drink',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_education',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_future_kids',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_relationship_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_religion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_salary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='deal_smoke',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeking',
            name='height_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='height_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='user_pic',
            field=models.FileField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frugality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pragmaticism',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
