# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0008_auto_20170328_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeking',
            name='relationship_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeking',
            name='religion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
