# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0008_auto_20170328_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='user',
            new_name='imguser',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profileuser',
        ),
        migrations.RenameField(
            model_name='seeking',
            old_name='user',
            new_name='seekinguser',
        ),
    ]
