# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0009_auto_20170328_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imguser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profileuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='seeking',
            old_name='seekinguser',
            new_name='user',
        ),
    ]
