# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0010_auto_20170328_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pic', models.FileField(default='img/default.png', upload_to='img')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gallery', to='match_dot_com.User')),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pics', to='match_dot_com.User'),
        ),
        migrations.AlterField(
            model_name='images',
            name='user_pic',
            field=models.FileField(default='img/default.png', upload_to='img'),
        ),
    ]
