# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0010_auto_20170328_2312'),
        ('match_dot_com', '0011_auto_20170328_2312'),
    ]

    operations = [
    ]
