# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_dot_com', '0012_merge_20170329_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
